### PR TITLE
V3 changes

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Using SimpleJson instead of Newtonsoft
 * Do not kill endpoint when can't send saga audit (log warning instead, same as in HB)
 * Do not include complex saga data properties (SI does not parse complex values, just shows json in a popup window when requested)
 * Allow custom saga data serialization (in case you do want to include some complex values)

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/servicecontrol-maintainers please review. Not sure why but the github UI does not allow me to assign reviewers :(

**Comment by SzymonPobiega** [comment]
@mikeminutillo I don't think we should deliberately cripple the plugin to make it usable only in dev environments.

**Comment by SzymonPobiega** [comment]
@mikeminutillo ? Ping @WilliamBZA

**Comment by WilliamBZA** [comment]
Sorry @SzymonPobiega, left my review in pending...

**Comment by SzymonPobiega** [comment]
Thanks @mikeminutillo and @WilliamBZA . I'll apply the same changes to V1 and V2

**Pull request merged**
